# EGIT 2024: preparación para clustering
Consolidación de los cuatro trimestres, con una fila por persona y trimestre como unidad provisional. No se asume seguimiento de la misma persona entre trimestres.

Estructura adaptada de los puntos 0–4 del parcial. Exploración, faltantes e IQR: `funciones_notebooks_profesor.txt`. Cruces, duplicados y reorganización de índices: código del parcial. Los ciclos recorren archivos o columnas, no personas. La exportación únicamente guarda resultados.

Las interpretaciones y decisiones son del estudiante. Listas vacías significan **pendiente**. No se ejecutan PCA ni k-means.

## Punto 0: Carga de datos
Se leen los 36 CSV extraídos, separados por `|`, sin cargar nuevamente los TXT ni los ZIP. Se conservan códigos como texto y ceros iniciales: tener dígitos no convierte una variable en cuantitativa.

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

RAIZ = Path.cwd()
assert (RAIZ / "Bases de datos").is_dir(), "Ejecuta desde K_means."
SALIDA = RAIZ / "Resultados"
SALIDA.mkdir(exist_ok=True)
carpetas = {
    1: "Base de datos-EGIT-Base Anonimizada-I trim2024",
    2: "Base de datos-EGIT-Base Anonimizada-II trim2024",
    3: "III Trim 2024",
    4: "Base de datos-EGIT-Base Anonimizada-IV trim2024",
}
modulos = ["CARACTERISTICAS_GENERALES", "EDUCACION", "FUERZA_DE_TRABAJO",
           "COMPLEMENTARIAS", "TURISMO", "EXCURSIONISMO", "HOGAR",
           "VIVIENDA", "VIVIENDA_USO_RECREATIVO"]
tablas = {}
inventario = []
for trimestre, carpeta in carpetas.items():
    for modulo in modulos:
        ruta = RAIZ / "Bases de datos" / carpeta / (modulo + ".csv")
        tabla = pd.read_csv(ruta, sep="|", dtype="string", encoding="utf-8",
                            keep_default_na=False, na_values=[""])
        assert tabla.columns.is_unique
        tablas[trimestre, modulo] = tabla
        inventario.append({
            "trimestre": trimestre, "modulo": modulo,
            "filas": len(tabla), "columnas": tabla.shape[1],
            "duplicados_exactos": int(tabla.duplicated().sum()),
            "archivo": str(ruta.relative_to(RAIZ)),
        })
inventario = pd.DataFrame(inventario)
assert len(inventario) == 36
display(inventario)

,trimestre,modulo,filas,columnas,duplicados_exactos,archivo
0,1,CARACTERISTICAS_GENERALES,31185,12,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
1,1,EDUCACION,30291,12,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
2,1,FUERZA_DE_TRABAJO,27401,17,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
3,1,COMPLEMENTARIAS,27401,31,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
4,1,TURISMO,27401,92,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
5,1,EXCURSIONISMO,27401,49,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
6,1,HOGAR,10746,23,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
7,1,VIVIENDA,10635,13,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
8,1,VIVIENDA_USO_RECREATIVO,171,13,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
9,2,CARACTERISTICAS_GENERALES,30542,12,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
10,2,EDUCACION,29656,12,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
11,2,FUERZA_DE_TRABAJO,26869,17,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
12,2,COMPLEMENTARIAS,26869,31,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
13,2,TURISMO,26869,92,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
14,2,EXCURSIONISMO,26869,49,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
15,2,HOGAR,10605,23,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
16,2,VIVIENDA,10502,13,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
17,2,VIVIENDA_USO_RECREATIVO,158,13,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
18,3,CARACTERISTICAS_GENERALES,30740,12,0,Bases de datos\III Trim 2024\CARACTERISTICAS_G...
19,3,EDUCACION,29848,12,0,Bases de datos\III Trim 2024\EDUCACION.csv
20,3,FUERZA_DE_TRABAJO,26962,17,0,Bases de datos\III Trim 2024\FUERZA_DE_TRABAJO...
21,3,COMPLEMENTARIAS,26962,31,0,Bases de datos\III Trim 2024\COMPLEMENTARIAS.csv
22,3,TURISMO,26962,92,0,Bases de datos\III Trim 2024\TURISMO.csv
23,3,EXCURSIONISMO,26962,49,0,Bases de datos\III Trim 2024\EXCURSIONISMO.csv
24,3,HOGAR,10540,23,0,Bases de datos\III Trim 2024\HOGAR.csv
25,3,VIVIENDA,10465,13,0,Bases de datos\III Trim 2024\VIVIENDA.csv
26,3,VIVIENDA_USO_RECREATIVO,132,13,0,Bases de datos\III Trim 2024\VIVIENDA_USO_RECR...
27,4,CARACTERISTICAS_GENERALES,29512,12,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
28,4,EDUCACION,28695,12,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
29,4,FUERZA_DE_TRABAJO,26017,17,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
30,4,COMPLEMENTARIAS,26017,31,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
31,4,TURISMO,26017,92,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
32,4,EXCURSIONISMO,26017,49,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
33,4,HOGAR,10267,23,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
34,4,VIVIENDA,10200,13,0,Bases de datos\Base de datos-EGIT-Base Anonimi...
35,4,VIVIENDA_USO_RECREATIVO,119,13,0,Bases de datos\Base de datos-EGIT-Base Anonimi...

## Punto 1: Entendimiento y exploración inicial
### 1.1 Dimensiones, tipos, faltantes y esquemas
Son conteos de registros, no estimaciones de población ponderadas por `Fex_c`.

In [2]:
calidad_origen = []
esquemas = []
for (trimestre, modulo), tabla in tablas.items():
    calidad_origen.append(pd.DataFrame({
        "trimestre": trimestre, "modulo": modulo, "variable": tabla.columns,
        "tipo_lectura": tabla.dtypes.astype(str).values,
        "faltantes": tabla.isna().sum().values,
        "porcentaje_faltante": (tabla.isna().mean() * 100).values,
        "valores_distintos": tabla.nunique().values,
    }))
    referencia = tablas[1, modulo].columns
    esquemas.append({
        "trimestre": trimestre, "modulo": modulo,
        "mismo_esquema_que_T1": tabla.columns.equals(referencia),
        "columnas_nuevas": ", ".join(tabla.columns.difference(referencia)),
        "columnas_ausentes": ", ".join(referencia.difference(tabla.columns)),
    })
calidad_origen = pd.concat(calidad_origen, ignore_index=True)
esquemas = pd.DataFrame(esquemas)
display(esquemas)
display(calidad_origen.sort_values("porcentaje_faltante", ascending=False).head(25))

,trimestre,modulo,mismo_esquema_que_T1,columnas_nuevas,columnas_ausentes
0,1,CARACTERISTICAS_GENERALES,True,,
1,1,EDUCACION,True,,
2,1,FUERZA_DE_TRABAJO,True,,
3,1,COMPLEMENTARIAS,True,,
4,1,TURISMO,True,,
5,1,EXCURSIONISMO,True,,
6,1,HOGAR,True,,
7,1,VIVIENDA,True,,
8,1,VIVIENDA_USO_RECREATIVO,True,,
9,2,CARACTERISTICAS_GENERALES,True,,
10,2,EDUCACION,True,,
11,2,FUERZA_DE_TRABAJO,True,,
12,2,COMPLEMENTARIAS,True,,
13,2,TURISMO,True,,
14,2,EXCURSIONISMO,True,,
15,2,HOGAR,True,,
16,2,VIVIENDA,True,,
17,2,VIVIENDA_USO_RECREATIVO,True,,
18,3,CARACTERISTICAS_GENERALES,True,,
19,3,EDUCACION,True,,
20,3,FUERZA_DE_TRABAJO,True,,
21,3,COMPLEMENTARIAS,True,,
22,3,TURISMO,True,,
23,3,EXCURSIONISMO,True,,
24,3,HOGAR,True,,
25,3,VIVIENDA,True,,
26,3,VIVIENDA_USO_RECREATIVO,True,,
27,4,CARACTERISTICAS_GENERALES,True,,
28,4,EDUCACION,True,,
29,4,FUERZA_DE_TRABAJO,True,,
30,4,COMPLEMENTARIAS,True,,
31,4,TURISMO,True,,
32,4,EXCURSIONISMO,True,,
33,4,HOGAR,True,,
34,4,VIVIENDA,True,,
35,4,VIVIENDA_USO_RECREATIVO,True,,

,trimestre,modulo,variable,tipo_lectura,faltantes,porcentaje_faltante,valores_distintos
736,3,EXCURSIONISMO,P7587S8A3,string,26962,100.000000,0
721,3,EXCURSIONISMO,P7587S4A3,string,26962,100.000000,0
998,4,EXCURSIONISMO,P7587S8A3,string,26017,100.000000,0
474,2,EXCURSIONISMO,P7587S8A3,string,26869,100.000000,0
463,2,EXCURSIONISMO,P7587S5A3,string,26869,100.000000,0
672,3,TURISMO,P7581S5A3,string,26962,100.000000,0
422,2,TURISMO,P7581S8A3,string,26869,100.000000,0
471,2,EXCURSIONISMO,P7587S7A3,string,26869,100.000000,0
459,2,EXCURSIONISMO,P7587S4A3,string,26869,100.000000,0
424,2,TURISMO,P7581S11A2,string,26869,100.000000,0
948,4,TURISMO,P7581S11A2,string,26017,100.000000,0
983,4,EXCURSIONISMO,P7587S4A3,string,26017,100.000000,0
212,1,EXCURSIONISMO,P7587S8A3,string,27401,100.000000,0
209,1,EXCURSIONISMO,P7587S7A3,string,27401,100.000000,0
197,1,EXCURSIONISMO,P7587S4A3,string,27401,100.000000,0
162,1,TURISMO,P7581S11A2,string,27401,100.000000,0
995,4,EXCURSIONISMO,P7587S7A3,string,26017,100.000000,0
686,3,TURISMO,P7581S11A2,string,26962,100.000000,0
201,1,EXCURSIONISMO,P7587S5A3,string,27400,99.996350,1
189,1,EXCURSIONISMO,P7587S2A3,string,27400,99.996350,1
735,3,EXCURSIONISMO,P7587S8A1,string,26961,99.996291,1
733,3,EXCURSIONISMO,P7587S7A3,string,26961,99.996291,1
410,2,TURISMO,P7581S5A3,string,26868,99.996278,1
451,2,EXCURSIONISMO,P7587S2A3,string,26868,99.996278,1
991,4,EXCURSIONISMO,P7587S6A3,string,26016,99.996156,1

### 1.3 Interpretación del estudiante
Pendiente: qué representa cada fila, población de interés y variables que podrían describir los grupos.

Los códigos `P...` requieren consultar preguntas, categorías y saltos del [diccionario oficial EGIT 2024](https://microdatos.dane.gov.co/index.php/catalog/864/data-dictionary).

## Punto 2: Calidad de datos y construcción de la base
### 2.0 Estado inicial: granularidad y duplicados
Módulos personales: `Directorio + Secuencia_p + Orden`. Hogar: `llave_hogar`. Vivienda: `Directorio`. Se añade el trimestre a la llave final.

En vivienda recreativa, se conserva cada registro dentro del hogar en columnas separadas. Su `Orden` no se cruza con el orden de una persona. No se suman ni promedian estos registros.

In [3]:
llave_persona = ["Directorio", "Secuencia_p", "Orden"]
llaves = {modulo: llave_persona for modulo in modulos}
llaves["HOGAR"] = ["llave_hogar"]
llaves["VIVIENDA"] = ["Directorio"]
llaves["VIVIENDA_USO_RECREATIVO"] = ["llave_hogar", "Orden"]
control_llaves = []
for (trimestre, modulo), tabla in tablas.items():
    clave = llaves[modulo]
    control_llaves.append({
        "trimestre": trimestre, "modulo": modulo, "llave": " + ".join(clave),
        "filas_sin_llave": int(tabla[clave].isna().any(axis=1).sum()),
        "duplicados_por_llave": int(tabla.duplicated(clave).sum()),
        "duplicados_exactos": int(tabla.duplicated().sum()),
    })
control_llaves = pd.DataFrame(control_llaves)
display(control_llaves)
assert control_llaves["filas_sin_llave"].sum() == 0
assert control_llaves["duplicados_por_llave"].sum() == 0, "Revisar llaves repetidas antes de cruzar."

,trimestre,modulo,llave,filas_sin_llave,duplicados_por_llave,duplicados_exactos
0,1,CARACTERISTICAS_GENERALES,Directorio + Secuencia_p + Orden,0,0,0
1,1,EDUCACION,Directorio + Secuencia_p + Orden,0,0,0
2,1,FUERZA_DE_TRABAJO,Directorio + Secuencia_p + Orden,0,0,0
3,1,COMPLEMENTARIAS,Directorio + Secuencia_p + Orden,0,0,0
4,1,TURISMO,Directorio + Secuencia_p + Orden,0,0,0
5,1,EXCURSIONISMO,Directorio + Secuencia_p + Orden,0,0,0
6,1,HOGAR,llave_hogar,0,0,0
7,1,VIVIENDA,Directorio,0,0,0
8,1,VIVIENDA_USO_RECREATIVO,llave_hogar + Orden,0,0,0
9,2,CARACTERISTICAS_GENERALES,Directorio + Secuencia_p + Orden,0,0,0
10,2,EDUCACION,Directorio + Secuencia_p + Orden,0,0,0
11,2,FUERZA_DE_TRABAJO,Directorio + Secuencia_p + Orden,0,0,0
12,2,COMPLEMENTARIAS,Directorio + Secuencia_p + Orden,0,0,0
13,2,TURISMO,Directorio + Secuencia_p + Orden,0,0,0
14,2,EXCURSIONISMO,Directorio + Secuencia_p + Orden,0,0,0
15,2,HOGAR,llave_hogar,0,0,0
16,2,VIVIENDA,Directorio,0,0,0
17,2,VIVIENDA_USO_RECREATIVO,llave_hogar + Orden,0,0,0
18,3,CARACTERISTICAS_GENERALES,Directorio + Secuencia_p + Orden,0,0,0
19,3,EDUCACION,Directorio + Secuencia_p + Orden,0,0,0
20,3,FUERZA_DE_TRABAJO,Directorio + Secuencia_p + Orden,0,0,0
21,3,COMPLEMENTARIAS,Directorio + Secuencia_p + Orden,0,0,0
22,3,TURISMO,Directorio + Secuencia_p + Orden,0,0,0
23,3,EXCURSIONISMO,Directorio + Secuencia_p + Orden,0,0,0
24,3,HOGAR,llave_hogar,0,0,0
25,3,VIVIENDA,Directorio,0,0,0
26,3,VIVIENDA_USO_RECREATIVO,llave_hogar + Orden,0,0,0
27,4,CARACTERISTICAS_GENERALES,Directorio + Secuencia_p + Orden,0,0,0
28,4,EDUCACION,Directorio + Secuencia_p + Orden,0,0,0
29,4,FUERZA_DE_TRABAJO,Directorio + Secuencia_p + Orden,0,0,0
30,4,COMPLEMENTARIAS,Directorio + Secuencia_p + Orden,0,0,0
31,4,TURISMO,Directorio + Secuencia_p + Orden,0,0,0
32,4,EXCURSIONISMO,Directorio + Secuencia_p + Orden,0,0,0
33,4,HOGAR,llave_hogar,0,0,0
34,4,VIVIENDA,Directorio,0,0,0
35,4,VIVIENDA_USO_RECREATIVO,llave_hogar + Orden,0,0,0

### 2.1 Ensamblaje por trimestre
Se conserva a todas las personas de características generales. Los prefijos indican procedencia y evitan sobrescribir columnas. Los indicadores `presente__MODULO` distinguen la ausencia de un registro completo de un vacío dentro del registro; **no certifican que una pregunta no aplique**.

Cada cruce comprueba unicidad, registros sin enlace y conservación de filas. Vivienda recreativa se reorganiza con `set_index().unstack()`, operaciones presentes en el parcial, sin agregación.

In [4]:
bases_trimestrales = []
control_cruces = []
procedencia = []
for trimestre in carpetas:
    base = tablas[trimestre, "CARACTERISTICAS_GENERALES"].copy()
    if trimestre == 1:
        procedencia.extend({
            "columna": c, "modulo": "CARACTERISTICAS_GENERALES", "variable_original": c
        } for c in base.columns)
    for modulo in modulos[1:]:
        fuente = tablas[trimestre, modulo].copy()
        if modulo == "VIVIENDA_USO_RECREATIVO":
            clave = ["llave_hogar"]
            fuente["presente"] = "1"
            derecha = fuente.set_index(["llave_hogar", "Orden"]).unstack("Orden")
            nombres = {
                par: modulo + "__" + par[0] + "__registro_" + str(par[1])
                for par in derecha.columns
            }
            procedencia.extend({
                "columna": nombre, "modulo": modulo, "variable_original": par[0]
            } for par, nombre in nombres.items())
            derecha.columns = [nombres[par] for par in derecha.columns]
            derecha = derecha.reset_index()
        else:
            clave = llaves[modulo]
            nombres = {c: modulo + "__" + c for c in fuente.columns if c not in clave}
            procedencia.extend({
                "columna": nombre, "modulo": modulo, "variable_original": original
            } for original, nombre in nombres.items())
            derecha = fuente.rename(columns=nombres)
        cobertura = derecha[clave].merge(
            base[clave].drop_duplicates(), on=clave, how="left",
            validate="one_to_one", indicator=True
        )
        huerfanas = int((cobertura["_merge"] == "left_only").sum())
        assert huerfanas == 0, f"Registros sin enlace: T{trimestre} {modulo}"
        indicador = "presente__" + modulo
        derecha[indicador] = True
        filas_antes = len(base)
        base = base.merge(derecha, on=clave, how="left", validate="many_to_one")
        base[indicador] = base[indicador].eq(True)
        assert len(base) == filas_antes
        control_cruces.append({
            "trimestre": trimestre, "modulo": modulo,
            "filas_antes": filas_antes, "filas_despues": len(base),
            "personas_sin_registro_modulo": int((~base[indicador]).sum()),
            "registros_huerfanos": huerfanas,
        })
    base["trimestre"] = trimestre
    base["anio"] = 2024
    bases_trimestrales.append(base)
df_consolidado = pd.concat(bases_trimestrales, ignore_index=True)
control_cruces = pd.DataFrame(control_cruces)
procedencia = pd.DataFrame(procedencia).drop_duplicates().reset_index(drop=True)
llave_final = ["trimestre"] + llave_persona
assert not df_consolidado.duplicated(llave_final).any()
assert len(df_consolidado) == inventario.loc[
    inventario["modulo"] == "CARACTERISTICAS_GENERALES", "filas"
].sum()
display(control_cruces)
display(df_consolidado.groupby("trimestre").size().rename("personas").to_frame())
print("Dimensión consolidada:", df_consolidado.shape)

,trimestre,modulo,filas_antes,filas_despues,personas_sin_registro_modulo,registros_huerfanos
0,1,EDUCACION,31185,31185,894,0
1,1,FUERZA_DE_TRABAJO,31185,31185,3784,0
2,1,COMPLEMENTARIAS,31185,31185,3784,0
3,1,TURISMO,31185,31185,3784,0
4,1,EXCURSIONISMO,31185,31185,3784,0
5,1,HOGAR,31185,31185,0,0
6,1,VIVIENDA,31185,31185,0,0
7,1,VIVIENDA_USO_RECREATIVO,31185,31185,30767,0
8,2,EDUCACION,30542,30542,886,0
9,2,FUERZA_DE_TRABAJO,30542,30542,3673,0
10,2,COMPLEMENTARIAS,30542,30542,3673,0
11,2,TURISMO,30542,30542,3673,0
12,2,EXCURSIONISMO,30542,30542,3673,0
13,2,HOGAR,30542,30542,0,0
14,2,VIVIENDA,30542,30542,0,0
15,2,VIVIENDA_USO_RECREATIVO,30542,30542,30108,0
16,3,EDUCACION,30740,30740,892,0
17,3,FUERZA_DE_TRABAJO,30740,30740,3778,0
18,3,COMPLEMENTARIAS,30740,30740,3778,0
19,3,TURISMO,30740,30740,3778,0
20,3,EXCURSIONISMO,30740,30740,3778,0
21,3,HOGAR,30740,30740,0,0
22,3,VIVIENDA,30740,30740,0,0
23,3,VIVIENDA_USO_RECREATIVO,30740,30740,30390,0
24,4,EDUCACION,29512,29512,817,0
25,4,FUERZA_DE_TRABAJO,29512,29512,3495,0
26,4,COMPLEMENTARIAS,29512,29512,3495,0
27,4,TURISMO,29512,29512,3495,0
28,4,EXCURSIONISMO,29512,29512,3495,0
29,4,HOGAR,29512,29512,0,0
30,4,VIVIENDA,29512,29512,0,0
31,4,VIVIENDA_USO_RECREATIVO,29512,29512,29192,0

           personas
trimestre
1             31185
2             30542
3             30740
4             29512

Dimensión consolidada: (121979, 278)

### 2.2 Diagnóstico de la base consolidada
Dos personas con las mismas respuestas no son necesariamente duplicados. Los controles conservan identificadores; ninguna alerta elimina columnas o filas automáticamente.

In [5]:
display(pd.DataFrame({
    "control": ["Duplicados exactos", "Duplicados persona-trimestre"],
    "cantidad": [df_consolidado.duplicated().sum(),
                 df_consolidado.duplicated(llave_final).sum()],
}))
calidad_consolidada = pd.DataFrame({
    "tipo": df_consolidado.dtypes.astype(str),
    "faltantes": df_consolidado.isna().sum(),
    "porcentaje_faltante": df_consolidado.isna().mean() * 100,
    "valores_distintos": df_consolidado.nunique(),
})
display(calidad_consolidada.sort_values("porcentaje_faltante", ascending=False).head(30))
display(calidad_consolidada.loc[calidad_consolidada["valores_distintos"] <= 1])

                        control  cantidad
0            Duplicados exactos         0
1  Duplicados persona-trimestre         0

,tipo,faltantes,porcentaje_faltante,valores_distintos
EXCURSIONISMO__P7587S8A3,string,121979,100.000000,0
VIVIENDA_USO_RECREATIVO__P38S3A1__registro_3,string,121979,100.000000,0
TURISMO__P7581S11A2,string,121979,100.000000,0
EXCURSIONISMO__P7587S4A3,string,121979,100.000000,0
EXCURSIONISMO__P7587S7A3,string,121978,99.999180,1
EXCURSIONISMO__P7587S2A3,string,121973,99.995081,6
TURISMO__P7581S8A3,string,121972,99.994261,4
TURISMO__P7581S5A3,string,121971,99.993441,5
VIVIENDA_USO_RECREATIVO__P38S2A1__registro_3,string,121970,99.992622,2
EXCURSIONISMO__P7587S5A3,string,121969,99.991802,7
VIVIENDA_USO_RECREATIVO__presente__registro_3,str,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__Secuencia_encuesta__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__P38S1__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__Secuencia_p__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__Directorio__registro_3,string,121968,99.990982,3
VIVIENDA_USO_RECREATIVO__Fex_c__registro_3,string,121968,99.990982,3
VIVIENDA_USO_RECREATIVO__P37__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__P38S2__registro_3,string,121968,99.990982,2
VIVIENDA_USO_RECREATIVO__P38S1A1__registro_3,string,121968,99.990982,3
VIVIENDA_USO_RECREATIVO__P38S3__registro_3,string,121968,99.990982,1
EXCURSIONISMO__P7587S6A3,string,121964,99.987703,8
VIVIENDA_USO_RECREATIVO__P38S3A1__registro_2,string,121964,99.987703,3
VIVIENDA_USO_RECREATIVO__P38S2A1__registro_2,string,121962,99.986063,5
EXCURSIONISMO__P7587S8A1,string,121962,99.986063,15
TURISMO__P7576S5,string,121956,99.981144,4
TURISMO__P7581S3A3,string,121955,99.980324,13
TURISMO__P7581S6A3,string,121954,99.979505,10
TURISMO__P7581S11A1,string,121952,99.977865,18
TURISMO__P7581S7A3,string,121952,99.977865,9
COMPLEMENTARIAS__P1996S8A1,string,121951,99.977045,7

,tipo,faltantes,porcentaje_faltante,valores_distintos
TURISMO__P7581S11A2,string,121979,100.000000,0
EXCURSIONISMO__P7587S4A3,string,121979,100.000000,0
EXCURSIONISMO__P7587S7A3,string,121978,99.999180,1
EXCURSIONISMO__P7587S8A3,string,121979,100.000000,0
HOGAR__Secuencia_p,string,0,0.000000,1
presente__HOGAR,bool,0,0.000000,1
VIVIENDA__Secuencia_p,string,0,0.000000,1
VIVIENDA__Secuencia_encuesta,string,0,0.000000,1
VIVIENDA__Orden,string,0,0.000000,1
presente__VIVIENDA,bool,0,0.000000,1
VIVIENDA_USO_RECREATIVO__Secuencia_p__registro_1,string,120457,98.752244,1
VIVIENDA_USO_RECREATIVO__Secuencia_p__registro_2,string,121911,99.944253,1
VIVIENDA_USO_RECREATIVO__Secuencia_p__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__Secuencia_encuesta__registro_1,string,120457,98.752244,1
VIVIENDA_USO_RECREATIVO__Secuencia_encuesta__registro_2,string,121911,99.944253,1
VIVIENDA_USO_RECREATIVO__Secuencia_encuesta__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__P37__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__P38S1__registro_2,string,121937,99.965568,1
VIVIENDA_USO_RECREATIVO__P38S1__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__P38S3__registro_3,string,121968,99.990982,1
VIVIENDA_USO_RECREATIVO__P38S3A1__registro_3,string,121979,100.000000,0
VIVIENDA_USO_RECREATIVO__presente__registro_1,str,120457,98.752244,1
VIVIENDA_USO_RECREATIVO__presente__registro_2,str,121911,99.944253,1
VIVIENDA_USO_RECREATIVO__presente__registro_3,str,121968,99.990982,1
anio,int64,0,0.000000,1

In [6]:
import re

TECNICAS_REDUNDANTES = [
    c for c in df_consolidado.columns
    if re.search(r"__(Secuencia_encuesta|Fex_c|llave_hogar|Directorio|"
                 r"Secuencia_p|Orden)(__registro_\d+)?$", c)
    or c.startswith("presente__") or "__presente__" in c
]

RENOMBRAR = {
    "Fex_c": "fex_trim",
    "VIVIENDA__area": "ciudad",
    "P6020": "sexo",
    "P6040": "edad",
    "P6050": "parentesco_jefe",
    "EDUCACION__P6170": "asiste_estudio",
    "EDUCACION__P6210": "nivel_educativo",
    "FUERZA_DE_TRABAJO__P6240": "actividad_principal",
    "HOGAR__P36": "hogar_viv_recreativa",
    "HOGAR__P545": "fuente_ingreso_principal",
    "HOGAR__P547": "ingreso_mensual_hogar",
    "TURISMO__P7570": "viajo_pernoctando",
    "TURISMO__P7571S1": "viaje_dentro_pais",
    "TURISMO__P7571S2": "viaje_fuera_pais",
    "TURISMO__P7573S1": "destino_depto",
    "TURISMO__P7573S2": "destino_municipio",
    "TURISMO__P7579": "motivo_no_viajar",
    "TURISMO__P7580": "motivo_viaje",
    "TURISMO__P7580S1": "viaje_con_quien",
    "TURISMO__P549": "fecha_inicio_viaje",
    "TURISMO__P549S1": "fecha_fin_viaje",
    "TURISMO__P15001": "reserva_por_app",
    "TURISMO__P7575": "transporte_principal",
    "TURISMO__P7576": "pago_paquete",
    "TURISMO__P7576S2": "paquete_n_personas",
    "TURISMO__P7576S3": "paquete_monto",
    "TURISMO__P7578": "gasto_total_viaje",
}
# alojamiento: S{n} = tipo usado, S{n}A1 = noches. El S7 usa A2, no A1.
for s in [1, 2, 3, 4, 5, 8, 10]:
    RENOMBRAR[f"TURISMO__P7574S{s}"] = f"aloj{s:02d}_uso"
    RENOMBRAR[f"TURISMO__P7574S{s}A1"] = f"aloj{s:02d}_noches"
RENOMBRAR["TURISMO__P7574S7"] = "aloj07_uso"
RENOMBRAR["TURISMO__P7574S7A2"] = "aloj07_noches"

# rubros: S{n} = ¿gastó?, A1 = monto, A2 = nº personas, A3 = submonto.
# El S11 no tiene A3.
for r in [1, 3, 4, 5, 6, 7, 8, 9, 10, 11]:
    RENOMBRAR[f"TURISMO__P7581S{r}"] = f"rubro{r:02d}_gasto_si"
    RENOMBRAR[f"TURISMO__P7581S{r}A1"] = f"rubro{r:02d}_monto"
    RENOMBRAR[f"TURISMO__P7581S{r}A2"] = f"rubro{r:02d}_n_personas"
    if r != 11:
        RENOMBRAR[f"TURISMO__P7581S{r}A3"] = f"rubro{r:02d}_monto_alt"

assert set(RENOMBRAR) <= set(df_consolidado.columns)
df_consolidado = (df_consolidado
                  .drop(columns=TECNICAS_REDUNDANTES)
                  .rename(columns=RENOMBRAR))
procedencia["columna"] = procedencia["columna"].replace(RENOMBRAR)

print("Técnicas eliminadas:", len(TECNICAS_REDUNDANTES))
print("Renombradas:", len(RENOMBRAR), "| Dimensión:", df_consolidado.shape)

Técnicas eliminadas: 47
Renombradas: 82 | Dimensión: (121979, 231)

In [7]:
def diagnostico(df, columnas, aplica):
    sub = df.loc[aplica, columnas]
    return pd.DataFrame({
        "n_aplica": len(sub),
        "no_nulos": sub.notna().sum(),
        "pct_faltante": (100 * sub.isna().mean()).round(2),
        "n_valores": sub.nunique(dropna=True),
    }).reset_index(names="columna").sort_values("pct_faltante")

es_viajero = df_consolidado["gasto_total_viaje"].notna()
cols_tur = [c for c in df_consolidado.columns
            if c.startswith(("rubro", "aloj"))
            or c in ("gasto_total_viaje", "transporte_principal", "motivo_viaje",
                     "pago_paquete", "fecha_inicio_viaje", "destino_depto")]

print("Viajeros con detalle:", int(es_viajero.sum()))
display(diagnostico(df_consolidado, cols_tur, es_viajero))

Viajeros con detalle: 6762

               columna  n_aplica  no_nulos  pct_faltante  n_valores
0         motivo_viaje      6762      6762          0.00          9
1        destino_depto      6762      6762          0.00         32
2   fecha_inicio_viaje      6762      6762          0.00        383
3           aloj01_uso      6762      6762          0.00          2
5           aloj05_uso      6762      6762          0.00          2
..                 ...       ...       ...           ...        ...
49   rubro06_monto_alt      6762        25         99.63         10
37   rubro03_monto_alt      6762        24         99.65         13
45   rubro05_monto_alt      6762         8         99.88          5
57   rubro08_monto_alt      6762         7         99.90          4
59  rubro11_n_personas      6762         0        100.00          0

[61 rows x 5 columns]

### 2.3 Selección, corrección de tipos y eliminación de filas
Completa las listas tras interpretar las tablas. `columnas_numericas` debe contener cantidades, no códigos categóricos. No reemplaces globalmente 9/99/999: su significado depende de la pregunta. Las conversiones se detienen si encuentran valores no convertibles.

In [8]:
RUBROS = [1, 3, 4, 5, 6, 7, 8, 9, 10]   # el 11 se descarta: 27 montos en todo 2024
ALOJ = [1, 2, 3, 4, 5, 7, 8, 10]

columnas_descartar = (
    [c for c in df_consolidado.columns
     if c.startswith(("EXCURSIONISMO__", "COMPLEMENTARIAS__",
                      "VIVIENDA_USO_RECREATIVO__"))]
    + [c for c in df_consolidado.columns if c.endswith("_monto_alt")]
    + [c for c in df_consolidado.columns if c.startswith("rubro11_")]
    + ["motivo_no_viajar", "destino_municipio", "TURISMO__P7573S3",
       "TURISMO__P7571S1A1", "TURISMO__P7571S1A2", "TURISMO__P7571S1A3",
       "TURISMO__P7571S2A1", "TURISMO__P7580S3"]
)
columnas_numericas = (
    ["edad", "ingreso_mensual_hogar", "gasto_total_viaje",
     "paquete_monto", "paquete_n_personas", "fex_trim"]
    + [f"rubro{r:02d}_monto" for r in RUBROS]
    + [f"rubro{r:02d}_n_personas" for r in RUBROS]
    + [f"aloj{a:02d}_noches" for a in ALOJ]
)
columnas_categoricas = [
    "ciudad", "sexo", "nivel_educativo", "actividad_principal",
    "hogar_viv_recreativa", "fuente_ingreso_principal", "motivo_viaje",
    "viaje_con_quien", "transporte_principal", "pago_paquete",
    "reserva_por_app", "destino_depto",
] + [f"rubro{r:02d}_gasto_si" for r in RUBROS] + [f"aloj{a:02d}_uso" for a in ALOJ]

reemplazos = {}
columnas_exigir_dato = ["gasto_total_viaje"]

assert not set(columnas_descartar) & set(llave_final)
assert not set(columnas_numericas) & set(columnas_categoricas)
assert set(columnas_descartar + columnas_numericas + columnas_categoricas
           + columnas_exigir_dato + list(reemplazos)) <= set(df_consolidado.columns)
df_trabajo = df_consolidado.drop(columns=columnas_descartar).copy()
df_trabajo = df_trabajo.replace(reemplazos)
conversiones = []
for columna in columnas_numericas:
    convertida = pd.to_numeric(df_trabajo[columna], errors="coerce")
    invalidos = df_trabajo[columna].notna() & convertida.isna()
    conversiones.append({"columna": columna, "no_convertibles": int(invalidos.sum())})
    assert not invalidos.any(), f"Revisa los valores no convertibles de {columna}."
    df_trabajo[columna] = convertida.astype(float)
for columna in columnas_categoricas:
    df_trabajo[columna] = df_trabajo[columna].astype("category")
if columnas_exigir_dato:
    df_trabajo = df_trabajo.dropna(subset=columnas_exigir_dato)
display(pd.DataFrame(conversiones, columns=["columna", "no_convertibles"]))
print("Filas retiradas:", len(df_consolidado) - len(df_trabajo))

                  columna  no_convertibles
0                    edad                0
1   ingreso_mensual_hogar                0
2       gasto_total_viaje                0
3           paquete_monto                0
4      paquete_n_personas                0
5                fex_trim                0
6           rubro01_monto                0
7           rubro03_monto                0
8           rubro04_monto                0
9           rubro05_monto                0
10          rubro06_monto                0
11          rubro07_monto                0
12          rubro08_monto                0
13          rubro09_monto                0
14          rubro10_monto                0
15     rubro01_n_personas                0
16     rubro03_n_personas                0
17     rubro04_n_personas                0
18     rubro05_n_personas                0
19     rubro06_n_personas                0
20     rubro07_n_personas                0
21     rubro08_n_personas                0
22     rubro09_n_personas                0
23     rubro10_n_personas                0
24          aloj01_noches                0
25          aloj02_noches                0
26          aloj03_noches                0
27          aloj04_noches                0
28          aloj05_noches                0
29          aloj07_noches                0
30          aloj08_noches                0
31          aloj10_noches                0

Filas retiradas: 115217

### 2.4 Tratamiento de faltantes
Se reutilizan `fillna()` y `mean()`. El estudiante debe definir una máscara booleana `aplica` por regla, según el formulario. La media se calcula solo sobre las filas aplicables. No se rellenan automáticamente saltos del cuestionario.

Formato: `{"columna": nombre, "metodo": "media" o "valor", "aplica": mascara, "valor": valor_elegido}`. La máscara debe conservar el índice de `df_trabajo`.

In [9]:
todos = pd.Series(True, index=df_trabajo.index)

reglas_imputacion = (
    [{"columna": f"rubro{r:02d}_monto", "aplica": todos,
      "metodo": "valor", "valor": 0.0} for r in RUBROS]
    + [{"columna": f"aloj{a:02d}_noches", "aplica": todos,
        "metodo": "valor", "valor": 0.0} for a in ALOJ]
    + [{"columna": "paquete_monto", "aplica": todos,
        "metodo": "valor", "valor": 0.0}]
)
registro_imputacion = []
for regla in reglas_imputacion:
    columna = regla["columna"]
    aplica = regla["aplica"]
    assert isinstance(aplica, pd.Series) and aplica.index.equals(df_trabajo.index)
    assert pd.api.types.is_bool_dtype(aplica) and not aplica.isna().any()
    antes = int(df_trabajo.loc[aplica, columna].isna().sum())
    if regla["metodo"] == "media":
        assert columna in columnas_numericas
        valor = df_trabajo.loc[aplica, columna].mean()
    else:
        assert regla["metodo"] == "valor"
        valor = regla["valor"]
    assert pd.notna(valor), "Valor de imputación no válido."
    df_trabajo.loc[aplica, columna] = df_trabajo.loc[aplica, columna].fillna(valor)
    despues = int(df_trabajo.loc[aplica, columna].isna().sum())
    registro_imputacion.append({
        "columna": columna, "metodo": regla["metodo"], "valor": valor,
        "imputados": antes - despues, "faltantes_aplicables": despues,
    })
registro_imputacion = pd.DataFrame(registro_imputacion, columns=[
    "columna", "metodo", "valor", "imputados", "faltantes_aplicables"
])
display(registro_imputacion)

          columna metodo  valor  imputados  faltantes_aplicables
0   rubro01_monto  valor    0.0       5383                     0
1   rubro03_monto  valor    0.0       5491                     0
2   rubro04_monto  valor    0.0       2621                     0
3   rubro05_monto  valor    0.0       5891                     0
4   rubro06_monto  valor    0.0       5949                     0
5   rubro07_monto  valor    0.0       5754                     0
6   rubro08_monto  valor    0.0       6222                     0
7   rubro09_monto  valor    0.0       6030                     0
8   rubro10_monto  valor    0.0       2987                     0
9   aloj01_noches  valor    0.0       6589                     0
10  aloj02_noches  valor    0.0       4849                     0
11  aloj03_noches  valor    0.0       6714                     0
12  aloj04_noches  valor    0.0       6667                     0
13  aloj05_noches  valor    0.0       2543                     0
14  aloj07_noches  valor    0.0       6686                     0
15  aloj08_noches  valor    0.0       6535                     0
16  aloj10_noches  valor    0.0       6663                     0
17  paquete_monto  valor    0.0       6481                     0

In [14]:
df_trabajo["duracion_dias"] = (
    pd.to_datetime(df_trabajo["fecha_fin_viaje"], errors="coerce")
    - pd.to_datetime(df_trabajo["fecha_inicio_viaje"], errors="coerce")
).dt.days
df_trabajo["log_gasto_total"] = np.log1p(df_trabajo["gasto_total_viaje"])

COLS_RUBRO = [f"rubro{r:02d}_monto" for r in RUBROS]
df_trabajo["suma_rubros"] = df_trabajo[COLS_RUBRO].sum(axis=1)
df_trabajo["coherencia"] = df_trabajo["suma_rubros"] / df_trabajo["gasto_total_viaje"]

print("Sin desglose (suma_rubros == 0):", int((df_trabajo["suma_rubros"] == 0).sum()))
display(df_trabajo.loc[df_trabajo["suma_rubros"] > 0, "coherencia"]
        .describe(percentiles=[.05, .25, .5, .75, .95]).round(3))

# los que no tienen desglose no sirven para composición
df_trabajo = df_trabajo.loc[df_trabajo["suma_rubros"] > 0].copy()

for r in RUBROS:
    df_trabajo[f"share_rubro{r:02d}"] = (
        df_trabajo[f"rubro{r:02d}_monto"] / df_trabajo["suma_rubros"])

# para que el Punto 3 analice las variables que realmente se van a usar
columnas_numericas += (["duracion_dias", "log_gasto_total", "suma_rubros"]
                       + [f"share_rubro{r:02d}" for r in RUBROS])

print("Base para clustering:", df_trabajo.shape)

Sin desglose (suma_rubros == 0): 2033

count    4729.000
mean        0.953
std         0.272
min         0.000
5%          0.378
25%         1.000
50%         1.000
75%         1.000
95%         1.000
max         5.000
Name: coherencia, dtype: float64

Base para clustering: (4729, 135)

### 2.5 Interpretación del estudiante
Pendiente: variables descartadas y motivo; faltantes frente a no aplica; correcciones; filas excluidas; método y alcance de cada imputación.

## Punto 3: Análisis descriptivo y tratamiento de atípicos
### 3.1 Estadísticos y frecuencias
Las salidas se activan al completar las listas de variables.

In [10]:
if columnas_numericas:
    display(df_trabajo[columnas_numericas].describe().T)
else:
    print("Pendiente: seleccionar variables cuantitativas.")
if columnas_categoricas:
    display(pd.concat({
        c: df_trabajo[c].value_counts(dropna=False) for c in columnas_categoricas
    }, names=["variable", "categoria"]).rename("frecuencia").to_frame())

,count,mean,std,min,25%,50%,75%,max
edad,6762.0,4.050237e+01,1.798756e+01,10.000000,2.600000e+01,3.900000e+01,5.400000e+01,9.300000e+01
ingreso_mensual_hogar,6752.0,3.981446e+06,3.793638e+06,98.000000,1.600000e+06,3.000000e+06,5.000000e+06,3.500000e+07
gasto_total_viaje,6762.0,9.827778e+05,1.539955e+06,98.000000,2.000000e+05,5.000000e+05,1.100000e+06,2.500000e+07
paquete_monto,6762.0,8.535378e+04,5.565467e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.040000e+07
paquete_n_personas,281.0,2.416370e+00,2.079049e+00,1.000000,1.000000e+00,2.000000e+00,3.000000e+00,3.000000e+01
fex_trim,6762.0,9.909766e+02,1.888260e+03,16.657892,1.630321e+02,3.115026e+02,6.865485e+02,1.940226e+04
rubro01_monto,6762.0,1.023955e+05,4.755994e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.200000e+07
rubro03_monto,6762.0,1.854746e+04,6.317868e+04,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.600000e+06
rubro04_monto,6762.0,1.970789e+05,3.876168e+05,0.000000,0.000000e+00,7.000000e+04,2.500000e+05,9.000000e+06
rubro05_monto,6762.0,2.360866e+04,1.393102e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+06
rubro06_monto,6762.0,2.888131e+04,1.411472e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+06
rubro07_monto,6762.0,2.690796e+04,1.039252e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.300000e+06
rubro08_monto,6762.0,1.628727e+04,1.241640e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,7.000000e+06
rubro09_monto,6762.0,7.999134e+04,3.182749e+05,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+06
rubro10_monto,6762.0,1.048775e+05,2.053725e+05,0.000000,0.000000e+00,4.000000e+04,1.500000e+05,9.000000e+06
rubro01_n_personas,1379.0,2.070341e+00,1.504270e+00,1.000000,1.000000e+00,2.000000e+00,3.000000e+00,2.000000e+01
rubro03_n_personas,1271.0,1.551534e+00,9.525657e-01,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,8.000000e+00
rubro04_n_personas,4141.0,1.956049e+00,1.338757e+00,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+01
rubro05_n_personas,871.0,1.918485e+00,1.329252e+00,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,1.000000e+01
rubro06_n_personas,813.0,2.264453e+00,1.416016e+00,1.000000,1.000000e+00,2.000000e+00,3.000000e+00,1.000000e+01
rubro07_n_personas,1008.0,1.895833e+00,1.166421e+00,1.000000,1.000000e+00,2.000000e+00,2.000000e+00,1.000000e+01
rubro08_n_personas,540.0,1.611111e+00,1.021416e+00,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,7.000000e+00
rubro09_n_personas,732.0,1.606557e+00,1.068571e+00,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,8.000000e+00
rubro10_n_personas,3775.0,1.904106e+00,1.244520e+00,1.000000,1.000000e+00,1.000000e+00,2.000000e+00,2.000000e+01
aloj01_noches,6762.0,1.254067e-01,1.097230e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.600000e+01
aloj02_noches,6762.0,1.011683e+00,2.396075e+00,0.000000,0.000000e+00,0.000000e+00,1.000000e+00,6.100000e+01
aloj03_noches,6762.0,2.351375e-02,6.726712e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,5.100000e+01
aloj04_noches,6762.0,3.564034e-02,3.713626e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.000000e+01
aloj05_noches,6762.0,3.425909e+00,6.659280e+00,0.000000,0.000000e+00,2.000000e+00,4.000000e+00,1.770000e+02
aloj07_noches,6762.0,4.185152e-02,5.330597e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,1.700000e+01
aloj08_noches,6762.0,1.486247e-01,1.216392e+00,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,4.800000e+01
aloj10_noches,6762.0,5.530908e-02,7.504191e-01,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,2.900000e+01

                      frecuencia
variable   categoria
ciudad     15                799
           17                537
           11                435
           68                389
           19                372
...                          ...
aloj07_uso 1                  76
aloj08_uso 2                6535
           1                 227
aloj10_uso 2                6663
           1                  99

[149 rows x 1 columns]

### 3.2 Distribuciones y correlación
El estudiante selecciona la variable que desea graficar.

In [11]:
variable_grafico = None
if variable_grafico is not None:
    assert variable_grafico in columnas_numericas
    sns.histplot(data=df_trabajo, x=variable_grafico)
    plt.show()
    sns.boxplot(data=df_trabajo, x=variable_grafico)
    plt.show()
if len(columnas_numericas) > 1:
    display(df_trabajo[columnas_numericas].corr())

,edad,ingreso_mensual_hogar,gasto_total_viaje,paquete_monto,paquete_n_personas,fex_trim,rubro01_monto,rubro03_monto,rubro04_monto,rubro05_monto,...,rubro09_n_personas,rubro10_n_personas,aloj01_noches,aloj02_noches,aloj03_noches,aloj04_noches,aloj05_noches,aloj07_noches,aloj08_noches,aloj10_noches
edad,1.000000,0.053687,0.037812,-0.010985,-0.102833,-0.011419,0.032285,0.086985,0.129284,0.036557,...,-0.038368,0.007231,0.087733,-0.018119,0.009426,-0.003345,0.042379,0.025989,0.005585,0.011353
ingreso_mensual_hogar,0.053687,1.000000,0.322931,0.074312,0.236468,0.126537,0.233574,0.063694,0.213371,0.188333,...,0.235262,0.178257,0.136359,0.129786,-0.009573,-0.010809,-0.104772,-0.029713,0.010505,0.011301
gasto_total_viaje,0.037812,0.322931,1.000000,0.344760,0.182022,-0.016107,0.634368,0.262347,0.571673,0.474664,...,0.623043,0.313185,0.038543,0.409335,-0.007186,0.067021,-0.037121,-0.018073,0.107809,0.050368
paquete_monto,-0.010985,0.074312,0.344760,1.000000,0.166674,0.023019,-0.024302,-0.008271,-0.051685,0.016549,...,0.120680,0.029002,-0.017531,0.183397,-0.003513,0.088613,-0.075133,-0.000037,-0.015753,-0.009765
paquete_n_personas,-0.102833,0.236468,0.182022,0.166674,1.000000,-0.026809,-0.016969,-0.017248,-0.014062,0.035645,...,1.000000,0.989481,NaN,0.037250,-0.053060,-0.021230,-0.070985,0.017000,0.039313,-0.023859
fex_trim,-0.011419,0.126537,-0.016107,0.023019,-0.026809,1.000000,0.022022,-0.050694,0.051466,-0.020212,...,0.083870,0.056451,0.051503,0.015630,-0.008311,0.017599,-0.018003,-0.013867,0.009279,-0.008507
rubro01_monto,0.032285,0.233574,0.634368,-0.024302,-0.016969,0.022022,1.000000,0.233983,0.528868,0.569914,...,0.433072,0.250798,-0.024611,0.374757,-0.004054,0.036050,-0.104116,-0.012658,0.072739,0.018062
rubro03_monto,0.086985,0.063694,0.262347,-0.008271,-0.017248,-0.050694,0.233983,1.000000,0.259299,0.217605,...,0.211558,-0.044175,-0.002115,0.149768,0.043340,-0.000630,0.058613,0.015521,0.035644,-0.016983
rubro04_monto,0.129284,0.213371,0.571673,-0.051685,-0.014062,0.051466,0.528868,0.259299,1.000000,0.388863,...,0.455541,0.313922,0.110976,0.200783,-0.002706,0.007712,0.088122,-0.012870,0.092958,0.045684
rubro05_monto,0.036557,0.188333,0.474664,0.016549,0.035645,-0.020212,0.569914,0.217605,0.388863,1.000000,...,0.323028,0.132140,0.053878,0.168168,0.010878,0.006090,0.011114,0.002336,0.000662,-0.008319
rubro06_monto,0.039270,0.140072,0.400067,0.016872,0.025242,0.010244,0.312331,0.251018,0.416324,0.221744,...,0.275876,0.180573,0.003219,0.151189,-0.006518,-0.003357,0.001701,-0.014436,0.033817,0.021300
rubro07_monto,0.079410,0.088798,0.250947,0.053778,-0.049712,-0.018002,0.107126,0.152601,0.268936,0.091197,...,-0.000603,0.100044,-0.001007,0.090211,-0.008269,0.002859,0.020183,0.002790,0.001984,0.022259
rubro08_monto,0.045328,0.030206,0.127827,-0.003754,0.031972,-0.015018,0.015244,0.051779,0.106465,0.042943,...,-0.037437,0.018085,0.020116,0.011893,0.002807,-0.007908,0.012896,0.012503,0.012404,-0.006336
rubro09_monto,0.083471,0.195578,0.514196,0.020385,0.025581,-0.002278,0.534277,0.361693,0.394943,0.368265,...,0.545645,-0.008648,0.010914,0.171669,-0.008787,0.001030,0.008611,0.006113,0.038048,-0.016489
rubro10_monto,0.109098,0.044000,0.237265,-0.044214,-0.052466,0.013467,0.192459,0.033345,0.441738,0.098078,...,0.071222,0.235056,0.005615,0.160514,0.009410,-0.006092,0.073606,-0.005997,0.025596,0.028058
rubro01_n_personas,0.039192,0.148594,0.368725,-0.017446,1.000000,0.003740,0.352090,0.053238,0.389777,0.214931,...,0.992536,0.949529,NaN,-0.046043,-0.039719,0.024772,0.011426,-0.036088,-0.002722,0.117500
rubro03_n_personas,-0.011347,0.186587,0.481071,0.097578,0.622078,0.038059,0.409476,0.263247,0.431387,0.314580,...,0.987228,0.967598,0.021832,0.122740,0.045155,-0.003126,-0.120821,-0.022445,0.079027,0.031539
rubro04_n_personas,0.014076,0.179708,0.311014,0.028593,0.863534,0.035330,0.226811,-0.014624,0.348073,0.153555,...,0.944817,0.923273,0.030659,-0.000077,0.006198,0.022083,-0.073606,-0.035638,0.003361,0.055268
rubro05_n_personas,-0.040456,0.317208,0.438095,0.040041,0.646648,0.093956,0.349028,-0.031114,0.489428,0.319860,...,0.982132,0.968544,0.063971,0.061708,-0.031419,-0.029041,-0.125818,-0.046575,0.013584,0.009464
rubro06_n_personas,0.065228,0.229523,0.406639,0.040960,0.797062,0.034288,0.315538,0.034302,0.418364,0.222490,...,0.962021,0.970102,-0.045938,0.117961,0.015750,-0.008383,-0.121509,-0.026495,-0.038329,0.151631
rubro07_n_personas,-0.071488,0.075675,0.317791,0.066716,0.821184,0.082745,0.223300,-0.045372,0.373035,0.100291,...,0.967537,0.929666,0.006300,0.005744,-0.027399,0.078641,-0.117090,-0.031936,0.044370,0.180183
rubro08_n_personas,0.038411,0.170764,0.231786,0.067417,0.659842,0.006562,0.148158,-0.049385,0.302308,0.043168,...,0.980947,0.948584,0.174854,-0.014159,-0.032714,0.033296,-0.106199,-0.012636,-0.030793,0.207075
rubro09_n_personas,-0.038368,0.235262,0.623043,0.120680,1.000000,0.083870,0.433072,0.211558,0.455541,0.323028,...,1.000000,0.967990,-0.027270,0.105290,NaN,0.080260,-0.116065,-0.016528,0.163308,0.013627
rubro10_n_personas,0.007231,0.178257,0.313185,0.029002,0.989481,0.056451,0.250798,-0.044175,0.313922,0.132140,...,0.967990,1.000000,0.037275,0.037641,0.007908,0.018049,-0.097504,-0.043829,0.003329,0.059841
aloj01_noches,0.087733,0.136359,0.038543,-0.017531,NaN,0.051503,-0.024611,-0.002115,0.110976,0.053878,...,-0.027270,0.037275,1.000000,-0.048265,-0.003996,-0.010971,-0.058808,-0.008975,-0.013967,-0.008425
aloj02_noches,-0.018119,0.129786,0.409335,0.183397,0.037250,0.015630,0.374757,0.149768,0.200783,0.168168,...,0.105290,0.037641,-0.048265,1.000000,-0.014578,-0.037203,-0.208359,-0.031533,-0.048654,-0.029808
aloj03_noches,0.009426,-0.009573,-0.007186,-0.003513,-0.053060,-0.008311,-0.004054,0.043340,-0.002706,0.010878,...,NaN,0.007908,-0.003996,-0.014578,1.000000,-0.003355,0.046268,0.081403,-0.004272,-0.002577
aloj04_noches,-0.003345,-0.010809,0.067021,0.088613,-0.021230,0.017599,0.036050,-0.000630,0.007712,0.006090,...,0.080260,0.018049,-0.010971,-0.037203,-0.003355,1.000000,-0.048304,-0.007536,-0.011728,-0.007075
aloj05_noches,0.042379,-0.104772,-0.037121,-0.075133,-0.070985,-0.018003,-0.104116,0.058613,0.088122,0.011114,...,-0.116065,-0.097504,-0.058808,-0.208359,0.046268,-0.048304,1.000000,-0.032064,-0.061371,-0.037213
aloj07_noches,0.025989,-0.029713,-0.018073,-0.000037,0.017000,-0.013867,-0.012658,0.015521,-0.012870,0.002336,...,-0.016528,-0.043829,-0.008975,-0.031533,0.081403,-0.007536,-0.032064,1.000000,-0.004804,-0.005788
aloj08_noches,0.005585,0.010505,0.107809,-0.015753,0.039313,0.009279,0.072739,0.035644,0.092958,0.000662,...,0.163308,0.003329,-0.013967,-0.048654,-0.004272,-0.011728,-0.061371,-0.004804,1.000000,-0.009007
aloj10_noches,0.011353,0.011301,0.050368,-0.009765,-0.023859,-0.008507,0.018062,-0.016983,0.045684,-0.008319,...,0.013627,0.059841,-0.008425,-0.029808,-0.002577,-0.007075,-0.037213,-0.005788,-0.009007,1.000000

### 3.3 Candidatos atípicos mediante IQR
Función original del profesor. Se aplica solo a las cantidades seleccionadas. Una marca no justifica automáticamente borrar o imputar el valor.

In [12]:
def detect_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    return data[(data[column] < lower_bound) | (data[column] > upper_bound)]

resumen_atipicos = []
for columna in columnas_numericas:
    candidatos = detect_outliers_iqr(df_trabajo, columna)
    resumen_atipicos.append({
        "variable": columna, "observados": int(df_trabajo[columna].notna().sum()),
        "candidatos_iqr": len(candidatos),
    })
resumen_atipicos = pd.DataFrame(resumen_atipicos, columns=[
    "variable", "observados", "candidatos_iqr"
])
display(resumen_atipicos)
if variable_grafico is not None:
    display(detect_outliers_iqr(df_trabajo, variable_grafico)[
        llave_final + [variable_grafico]
    ].head(20))

                 variable  observados  candidatos_iqr
0                    edad        6762               0
1   ingreso_mensual_hogar        6752             332
2       gasto_total_viaje        6762             673
3           paquete_monto        6762             281
4      paquete_n_personas         281               1
5                fex_trim        6762            1070
6           rubro01_monto        6762            1379
7           rubro03_monto        6762            1271
8           rubro04_monto        6762             441
9           rubro05_monto        6762             871
10          rubro06_monto        6762             813
11          rubro07_monto        6762            1008
12          rubro08_monto        6762             540
13          rubro09_monto        6762             732
14          rubro10_monto        6762             454
15     rubro01_n_personas        1379              14
16     rubro03_n_personas        1271              70
17     rubro04_n_personas        4141             524
18     rubro05_n_personas         871             107
19     rubro06_n_personas         813               7
20     rubro07_n_personas        1008             109
21     rubro08_n_personas         540              38
22     rubro09_n_personas         732              50
23     rubro10_n_personas        3775             457
24          aloj01_noches        6762             173
25          aloj02_noches        6762            1108
26          aloj03_noches        6762              48
27          aloj04_noches        6762              95
28          aloj05_noches        6762             513
29          aloj07_noches        6762              76
30          aloj08_noches        6762             227
31          aloj10_noches        6762              99

### 3.4 Tratamiento e interpretación del estudiante
Pendiente: revisión y justificación. Si decides retirar registros, indica sus índices. No se excluyen candidatos IQR automáticamente.

In [13]:
indices_excluir = []
assert set(indices_excluir) <= set(df_trabajo.index)
df_preparado = df_trabajo.drop(index=indices_excluir).copy()
assert not df_preparado.duplicated(llave_final).any()
display(pd.DataFrame({
    "etapa": ["Consolidada", "Después de faltantes", "Después de revisión de atípicos"],
    "filas": [len(df_consolidado), len(df_trabajo), len(df_preparado)],
    "columnas": [df_consolidado.shape[1], df_trabajo.shape[1], df_preparado.shape[1]],
}))

                             etapa   filas  columnas
0                      Consolidada  121979       231
1             Después de faltantes    6762       122
2  Después de revisión de atípicos    6762       122

## Punto 4: Preprocesamiento para el modelado — punto de parada
### 4.1 Selección y verificación previa
La matriz requiere decisiones sobre población, variables, categorías, faltantes y escala. Los identificadores y factores se conservan para trazabilidad; no son características por defecto.

La reducción de dimensionalidad queda pendiente según las variables. No se ejecutan PCA, codificación, escalado ni k-means.

In [15]:
variables_modelado = (
    [f"share_rubro{r:02d}" for r in RUBROS]
    + ["log_gasto_total", "duracion_dias"]
)
decisiones_revisadas = True
X_previo = df_preparado.loc[:, variables_modelado].copy()
display(pd.DataFrame({
    "tipo": X_previo.dtypes.astype(str),
    "faltantes": X_previo.isna().sum(),
    "valores_distintos": X_previo.nunique(),
}))
print("Decisiones revisadas:", decisiones_revisadas)
print("Variables seleccionadas:", len(variables_modelado))
print("Estado: base consolidada disponible; matriz para clustering pendiente.")

KeyError: "None of [Index(['share_rubro01', 'share_rubro03', 'share_rubro04', 'share_rubro05',\n       'share_rubro06', 'share_rubro07', 'share_rubro08', 'share_rubro09',\n       'share_rubro10', 'log_gasto_total', 'duracion_dias'],\n      dtype='str')] are in the [columns]"

### 4.2 Exportación y comprobación
`egit_2024_consolidada.csv.gz` reúne los cuatro trimestres. `egit_2024_preparacion_actual.csv.gz` guarda las decisiones configuradas, **no certifica que esté listo para k-means**. Son CSV comprimidos con gzip.

Se guardan los controles completos y la procedencia de las columnas.

In [ ]:
ruta_consolidada = SALIDA / "egit_2024_consolidada.csv.gz"
df_consolidado.to_csv(ruta_consolidada, index=False, compression="gzip")
df_preparado.to_csv(SALIDA / "egit_2024_preparacion_actual.csv.gz",
                   index=False, compression="gzip")
for nombre, reporte in {
    "inventario": inventario, "calidad_origen": calidad_origen, "esquemas": esquemas,
    "control_llaves": control_llaves, "control_cruces": control_cruces,
    "procedencia_columnas": procedencia, "imputaciones": registro_imputacion,
    "atipicos": resumen_atipicos,
}.items():
    reporte.to_csv(SALIDA / (nombre + ".csv"), index=False)
calidad_consolidada.to_csv(SALIDA / "calidad_consolidada.csv", index_label="columna")
recarga = pd.read_csv(ruta_consolidada, dtype="string",
                     keep_default_na=False, na_values=[""])
assert recarga.shape == df_consolidado.shape
assert recarga.equals(df_consolidado.astype("string"))
print("Exportación verificada:", ruta_consolidada.name, recarga.shape)

Exportación verificada: egit_2024_consolidada.csv.gz (121979, 278)

### 4.3 Pendientes para continuar
Interpretar las tablas, elegir población y variables, consultar categorías y saltos, configurar limpieza e imputación y revisar atípicos. Luego decidir representación y escala, reducción de dimensionalidad si corresponde y finalmente k-means.

Se revisó el [tutorial de Real Python solicitado](https://realpython.com/k-means-clustering-python/); queda como referencia para la siguiente etapa, sin incorporar su código. La consulta de módulos usa el [diccionario DANE EGIT 2024](https://microdatos.dane.gov.co/index.php/catalog/864/data-dictionary) y [vivienda recreativa](https://microdatos.dane.gov.co/index.php/catalog/864/data-dictionary/F3?file_name=Vivienda+uso+recreativo).

Apoyo de IA: programación y comprobaciones técnicas. Interpretación, decisiones metodológicas y conclusiones: pendientes del estudiante.